import type { ExpertInterview } from "../types";

export const raviSanthanam: ExpertInterview = {
  slug: "ravi-santhanam",
  project: "ai-led-personalization",
  perspective: "buyer",

  metaTitle:
    "HDFC Bank's Digital Transformation and Customer Experience Journey Amid the Pandemic",
  metaDescription:
    "Ravi Santhanam, Chief Marketing Officer at HDFC Bank, on revenue marketing, next best action across a five crore customer base, and breaking conventions during lockdown.",

  title:
    "HDFC Bank's Digital Transformation and Customer Experience Journey Amid the Pandemic",
  person: {
    name: "Ravi Santhanam",
    role: "Chief Marketing Officer",
    company: "HDFC Bank",
  },

  thumbnail: "/experts/ravi-santhanam.png",
  thumbnailAlt: "Ravi Santhanam, Chief Marketing Officer at HDFC Bank",

  intro: [
    "In this discussion, Ravi Santhanam, Chief Marketing Officer at HDFC Bank, shared their approach to personalising the customer experience, what it means for HDFC Bank to be contextual and relevant in their customer interactions, and why the use of analytics and machine learning is critical for marketers today. Ravi also shared important insights into the consumer banking experience and the impact of, and response to, the pandemic.",
  ],

  highlights: [],

  pullQuote:
    "In my view, it is no longer a choice for marketers, the use of new-age data science and AI or ML technology. This is what customers are looking for.",

  exchanges: [
    {
      question:
        "You have been a senior marketing leader for over two decades. I wanted to start this discussion with your journey as a marketer: what impact have you observed of the changing marketing landscape in the industry?",
      answer: [
        "I am an accidental marketer. I was almost seven years in hardcore finance, working for ICICI Bank on the tech side and then a UK based energy company on the equity side. So I am a business guy, and then I moved into telecom to handle multiple business roles, and then moved into marketing pretty late in the day.",
        "Revenue marketing is what I look at. I do not look at marketing for the sake of branding or communication; marketing for the sake of anything else is not acceptable to me. I have defined marketing in my own language as understanding consumers, creating demand, and generating revenue.",
        "So from that perspective, it is more about bringing revenue on the table for the company. Obviously, we talk to the consumers, and it is about how you solve the consumer's problems. It has to be a win for the customer, it has to be a win for the company, and it has to be a win against the competition, and if you can do that, you are going to be always on top.",
        "I strongly believe that while we all have a role to play in the function we work in, one needs to consider how it impacts the end delivery of a product or a service for the customer. If you understand that and can improve on that, the company does well.",
      ],
    },
    {
      question:
        "You have worked in two of the most significant consumer-facing industries, telecom and banking. What are your observations when it comes to technology in marketing? What are the best practices and challenges that you have observed?",
      answer: [
        "When we look at it from a consumer perspective, things have fundamentally changed over time. From an organisation's perspective, you want to reach the consumer. You want to communicate with the customer saying, this is what I have, and this is the problem of yours that I can solve. When television came, everybody said it has all changed, and there were big changes in terms of the one to many communication, and that is how it was for a long period.",
        "As a brand, I talk to my customers; the operating word is talking to my customers. I will say, this is the product I have, and this is the benefit that you may have. There is always this consumer benefits ladder as marketers, where we keep on pushing ourselves in terms of what is the rational need that we can take care of and the emotional need at the top level that we can fulfil based on what we serve the consumer with. We keep pushing ourselves in that direction.",
        "A brand was invariably built by the company having a thought in its mind and communicating that to the customer, and there was an intermediary standing in between. It could be the agency, could be the distributor through which we were communicating with the customer. That was how marketing has happened for a long, long time.",
        "But then something which changed this way of looking at things was the advent of digital technology, because it gave the power back to the consumer to talk to us. Now the talking to had to change to talking with the customer; earlier the marketer had control over the brand and could have the narrative in control.",
        "Now with digital technologies in place, and social media coming together and devices in the hands of the consumers, what is suddenly happening is the consumer can talk back, and over a period of time the trust factor, which used to be with only the brand, slowly started to shift.",
        "People now say, okay, I am going to trust the bank as much as I am going to trust my neighbours and friends, as much as I am going to trust this person who I do not even know, because they are going and rating the product I want to buy. Why would they give a poor rating, or why would thousands of people give a good rating? So suddenly, the consumer's ability to connect in this internetworked world has moved who we trust to unknown people.",
        "Unknown people's ability to review and rate a product that you want to buy influences your choices. So the narrative of who talks about the brand is influencing what a brand can do and cannot do. This is a very different sphere in which we are operating now. COVID or not, nothing changes this perspective.",
        "The second thing which also comes out of this is data proliferation. There is so much information that we all leave behind at various places. While everybody talks about privacy and other things, in the banking industry, which I am now part of, I see various changes.",
        "What is trust? Some decades back, trust used to be about keep my money safe. Bank as trustworthy means whenever I want my money, I will get it back. That was the only condition on which trust was defined in the banking industry. Now, when we looked at what the trust definition is, it has changed.",
        "The safety and the trust that we talked about in banking keeps coming back to money when there is an issue of a financial crisis. Maybe once in a decade, that happens. If it does not happen, what is trust? The definition of trust needs to be: if you know so much about me, why can you not be relevant?",
        "Customers voluntarily give us information, because we do KYC, so obviously we know who the customer is. We also know where the money is coming from, where the money of the customer is going. Today, they are experiencing an Amazon, a Facebook, and the Ubers of the world as the same consumer. Data is being used to create more and more new and richer experiences.",
        "That data is also something that people do not understand how companies are getting. That is the real core technology that many people will not understand how it all works: cookies, identification, triangulation, and a humongous amount of data being consolidated to get some insights into the personas of the customer.",
        "Customers voluntarily give us data in the case of HDFC Bank or any other bank in the industry. Because of the laws of the land and the regulation, you need to give me a lot more information to start the account, and then when you actually put in the money. We know when you swipe your credit card, and we know where you stay, what your electricity bill is, what it is that you are purchasing on your credit card. If you go to say a Vijay Sales and swipe, I can easily figure out that you actually bought a TV.",
        "We have a tremendous obligation to keep this data secure. That is fine, and it is all within the firewall for the bank. Now the question is, now that you know so much about me, why are you telling me something which I am not interested in and is irrelevant? So what should I talk about? Technology forces me to talk with them and not talk to them.",
        "There is an interaction possibility now, so as a brand, are we talking with our customers now or talking to them? I cannot come and suddenly have a conversation with you, and it is unrelated. If I have to increase the relevancy quotient, I need to understand more. Are you using the data you already have?",
        "For example, if you think I am a 45-year-old male already owning a car, do you think I would want to buy a two-wheeler? Why are you sending me a two-wheeler loan offer? Can you not see that an insurance premium payment is made in the name of some insurance company every year at a certain point in time? It has to be vehicle insurance because I am paying a general insurance company. Can you not see that I own a car? Anyway, every month I am using a credit card to buy fuel.",
        "So the customer is going to be very unhappy if you are irrelevant. The relevancy question keeps increasing in order of magnitude when we have this kind of data. If you do not use this data to increase the relevance when you are talking with customers, then what is marketing doing?",
      ],
    },
    {
      question:
        "Given that there is this massive amount of data and analytics going on, is there any use of AI-led personalisation wherein you are trying to be contextual and relevant, and could you share some use cases which are AI-driven at your end?",
      answer: [
        "We believe this is the directional wave, and the second aspect of being relevant is about presence. As marketers, we have always chased customers, and the choice of the media that we have always used to communicate with our customers has been the medium that the customer is actually using. As mediums continue to change, from press to a magazine to television, to social media to the internet, I need to be present in every media where the customer is present.",
        "Presence is also about a soft presence. When you as a customer are thinking about a need, I need to be present wherever you are. So one is an aspect of relevance, that I need to be relevant for you. I also need to be wherever you are, and whenever you think you need something.",
        "How do I know where you are and what you need from our brand? As a bank, you have a tremendous amount of user-generated data. The first thing is to put it all together, and when you put it together, you are in a position to do a lot more effective one to one communication, about what is the right thing for the customer to do at any point in time, and what needs to be done next.",
        "When you have to crunch this kind of data, you need to have phenomenal computing power. We need to have human intelligence which is supported by machine language and learning algorithms. How good are you in terms of looking at a certain trend and then predicting that somebody else does it? There is a set of people who might end up doing it, and when it comes to natural life, we can very easily segment and predict.",
        "For example, if we look at a typical corporate employee in India, they will first join a company somewhere between the ages of 23 to 25. They will open a bank account for cash, maybe they want to buy a bike, and then they will go ahead and take a credit card. After marriage only can they even think of a life insurance policy. If a child is born, you suddenly start thinking that there is somebody who is dependent on me, and life insurance can be talked about at that point.",
        "When they start earning a little bit extra, we will come in to talk about tax saving instruments. Initially, the tax-saving instrument will be a simple NPS or it could be a mutual fund. From there, you will start building your portfolio, and until the time you are 32 or 33, we are not talking about home loans.",
        "In between, there will be a car loan, and after that a home loan, maybe I will talk about a second home, or I will start talking to you about investments, then I will start to talk to you about personal loans for a holiday, or a revamp of the house or something of that sort. Then I will talk to you about increasing your investment or insurance cover. Over a period of time, I will start talking about regular investments and then finally a retirement solution. Very natural, right?",
        "Now you have to prove it day in day out, and not only on that level but also at a moment marketing level. How are you going to structure the data, so how are you going to get this natural intelligence shifted to the machine? Maybe once in two to three years people take these kinds of decisions, but on a day to day basis we make a lot of financial decisions. What should I spend and what money do I have in balance? If I swipe my credit card, what will happen? This is all day to day stuff.",
        "Between the mix of today's financial decisions and tomorrow's financial decisions, unless you have a huge amount of data crunching capability and the ability to do it on the fly, it is not going to happen.",
        "What we have done is invest in a lot of technology which predicts what is going to be the next best action for any one of our customers. On each of these dimensions, where is the customer signalling what they may do next? Then we can correspondingly go and talk with them and say, if you are interested in this area, this is what we do.",
        "For example, somebody is going and breaking a fixed deposit. If there is no cash in your account and I am breaking the fixed deposit, it is a very different meaning. If a customer would break a fixed deposit of fifty lakh, when cash in the bank says only 1 lakh, it is probably an emergency. But if you have one crore in the bank, it is a very conscious decision. There is something more that is happening there, and I need a little more data to figure it out. One has to understand the personal history of the last two to three years.",
        "I know there are these triggers, and I have signals available for people who are breaking a deposit of fifty lakh with one crore in the bank. They have gone ahead and taken a conscious decision to go ahead and buy a house or make some serious investment. If the investment is made through me, then I need not bother talking with the customer.",
        "If your intelligence can figure out the customer has an emergency, you can go back and say, here is an opportunity, do not break the fixed deposit, I will give you a loan on this deposit. That loan can be taken out by just pressing two buttons, so that we can continue to earn interest. This understanding is easy to do for one person when I give you an example. But how do I do it for a five crore customer base? It is not possible without the involvement of technology, without the ability to personalise based upon context. By understanding the full data, I can understand the first context, and then I can personalise, and then I can hyper-personalise. Just looking at the basic customer record, you cannot generally be very good in your dealings with customers.",
        "In my view, it is no longer a choice for marketers, the use of new-age data science and AI or ML technology. This is what customers are looking for. How to use it and what technology is your choice, but if you are not going to use it, I think you are going to be irrelevant.",
      ],
    },
    {
      question:
        "How have you ensured your consumer base was served well during the lockdown phase? As a marketer, what changes have you observed?",
      answer: [
        "First off, it is the first time in our lifetime that you are seeing a health crisis like this. A health crisis leads to a public policy change. There are the social dynamics which change; social distancing is something that is happening. There are a lot of consumer behaviour changes. Some of them are here to stay, some of them will increase, some of them will vanish. These things are extremely difficult to predict as we speak. We will learn over a period of time.",
        "One of the things we are very sure about is digital will continue to increase its space. The space was anyway growing, and social distancing has pushed people to digital. That is not going to change; I think that we will get pushed further and further. The second thing is that experience is key. If the experience is not being delivered even today, people are not going to like it. They are sitting at home, they have a lot of time, and everybody is looking at the experience which brands are providing.",
        "Now, if you look at those who are actually the winners, they are always the people who have been investing in customer experience. They are the people who leverage technology to solve the consumer experience problem.",
        "Today, people are very worried about personal safety and family safety. That has also slowly translated into income uncertainty, and this income uncertainty has two angles. People are thinking, first, whether I have the money, and second, how long will it last? People were growing their salary or were looking forward to growth in the next three years, and this has put paid to those hopes; it may now happen in five years or ten years. This is creating a lot of worries in the minds of people.",
        "The first thing we decided is there is no rule book. Whenever we encounter any kind of problem, we have always looked back in history. Whether it is your personal experience or the wider industry experiences or even cross-industry experiences, you will not find examples of people who have come out of this situation. So the first thing we decided amongst ourselves is there is no rule. We told ourselves that we would break conventions and be ready for the new. Anything and everything that we need to do as the marketing organisation, we will look at it. I read an interesting thing which somebody said: do not restart, start. Interesting coinage of words, but it is a very powerful coinage of words in our understanding. Restart assumes that I stopped something for a reason, and everything is back to normal. Whereas start means I am going to look at what is available today, and I want to see if it will work for me or not.",
        "We want to start with the current context. So primarily, we started looking at reimagining the customer interactions, because people are suddenly not coming into your branches thanks to social distancing and virus fear. We are a bank, and we have a lot of physical sales capability where people came and met with you. If you want to take insurance, you want somebody to come and sit in front of you and explain. People who are used to having that physical sale need to be converted into a tele-sale or video-sale customer. Now, we get a lot of clues from your body language when speaking to you in person. On the telephone, people are not as qualified to understand how you are reacting. So I need to learn a lot of new skills, because body language is not going to be a key influencer any more. In which case voice empathy is key to looking at things like: are you allowing the customer to speak? Are you countering the customer?",
        "Looking at this kind of stuff, we started thinking, how can we reimagine our customer interactions? How do I embrace digital and also look at the fact that there are a lot of senior citizens? Many people are not comfortable using the mobile or the desktop to transfer funds or to take cash out. We have to help them. So how do I help people move from offline to online?",
        "We also see that there is a lot more do it yourself possible in India. We are a country where we expect service, like washing your car, driving your car and so on. Whereas do it yourself in western economies is very famous. Mainly because of this virus, in India we have started doing a lot of things at home. That might continue after this period if people can manage it. Who knows what is going to be possible, so we need to be more digital. This digital transformation is very different from the digital we have always followed. It has to be as agile and as digital as can be. It is not going to be one of those small micro-changes that we do. Suddenly within this one and a half months, the organisation has come up with a new car loan; they have come up with instant Demat account opening, and also starting our normal savings account.",
        "Within these 45 days, we have converted many of our journeys into digital. Earlier, we were very clear that the journey for a bank account should be made in a physical branch, because we never are interested in a zero balance. At the end of the day, people are going to downgrade because of income uncertainty. As a financial service provider, how are you going to have some of these products introduced? For example, we always had long term loans, but we might have to go into short term loan products for people who do not want to borrow for a longer period. It is a very different set of people who will borrow now, and borrowing for a European holiday, for example, is almost out, even if you might have the money.",
        "We have lots of uncertainty from these areas, but there are enough people to talk to about our products, because they might have to tide over a three month or six-month cash crunch. Also, what we always wanted to do is to engage with our employees. They have been working in the days of lockdown; there are a lot of people in our team who are brave souls too, going to the branches on a day to day basis, so they fundamentally kept the economy moving, whatever economy was there. The hard stuff would have happened there on the ground, so we wanted to convey a lot of attention to our people, that you can start.",
        "So as a brand, we did two campaigns that were mind-blowingly different. Normally we would never actually put our brand logo on the ground. We called it a Safety Grid, with our brand logo as a beautiful centre spread that has four arrows. From an outside perspective, it will look like a nice rectangle or a square. We printed it and put it on the ground with a distance of one and a half metres away so that people can stand on it, and they can practise social distancing across 5000 shops, primarily pharmacies and groceries.",
        "There was a huge hue and cry, with people saying, how can you put your brand on the ground? We told them very simply: put it. We are no bigger than the society that we operate in, and society is undergoing a crisis. We are known for safety and security. If my safety and security can be taken to the ground to help society, then I will do it. When I put the brand on the ground and ask people to stand on it to practise social distancing, the entire company suddenly looks at it and says, wow, here is the company coming and telling everybody to stand on my brand logo. I feel that the brand affinity for the employees increased dramatically wherever I have done this. Obviously, at 5000 outlets I will not be able to cover the entire audience, but the employee's ability to perceive things is very different.",
        "To follow up on that campaign, we also wanted to create engagement, and we wanted to create hope. People are very worried, and we want to overcome it, and we will overcome it. So we wanted to inspire people. We tied up with A R Rahman, and we came up with a music video called Hum Haar Nahin Maanenge. You might say that everybody has done a music video in this kind of situation. But you must understand HDFC Bank has never advertised in this way, and we have never done this kind of brand investment. We got A R Rahman and Prasoon Joshi to come and compose during the lockdown period, and hundreds of big names are all singing for us together in a song, and we spent a lot of money on that.",
        "What happened is suddenly the entire organisation looks at it and says, wow, we are different. Suddenly the employees' energy levels are very different; they get that energy and inspiration, that I can do a lot more and nothing is going to stop me. You have to follow that up with actions on the ground, and you need to break conventions. So when you get a message back into the system, they understand these are not empty words. My consumers understand these are not empty words. HDFC Bank will break the rules, and we will be bold. We will break the mould and be ready for the new; my consumers know for a fact that never has HDFC Bank done anything like this before. My consumers would see the brand logo on the ground and remember that. My consumer will say, yes, I saw that video by HDFC Bank. We had two and a half crore views on that video. People would have seen it and said, yes, there is this energy, which I am getting. This is what is going to stand me in good stead.",
        "From a brand perspective, and from a hardcore digital technology perspective, we have effectively used this time to get our models sharpened. We are having a lot of discussion about whether our models will work in these kinds of situations. Ultimately, you will not know until the time the event passes by.",
      ],
    },
  ],
};
