import type { ExpertInterview } from "../types";

export const aaronFoo: ExpertInterview = {
  slug: "aaron-foo",
  project: "south-east-asia-response-guide",
  perspective: "buyer",

  metaTitle: "Redesigning Supply Chain",
  metaDescription:
    "Aaron Foo, Head of Product Strategy at iCar Asia, on speed and accessibility, bringing the final mile back offline, removing middlemen, and shipping an MVP not a car.",

  title: "Redesigning Supply Chain",
  person: {
    name: "Aaron Foo",
    role: "Head of Product Strategy",
    company: "iCar Asia",
  },

  thumbnail: "/experts/aaron-foo.jpg",
  thumbnailAlt: "Aaron Foo, Head of Product Strategy at iCar Asia",

  intro: [
    "Aaron Foo discusses the importance of speed, consumer accessibility, and integrating back offline experiences all over again for digital-first businesses.",
    "In this Research NXT interview, Aaron Foo, Head of Product Strategy at iCar Asia and an author, talks to us about his journey of co-writing the MPH bestseller Habitudes: 21 Days to Change Your Life, and his experience with the technology side of developing some very smart digital-first products. He particularly discusses the human aspect of everything, which is very important.",
  ],

  highlights: [
    "His observations on the evolution of the digital-first industry.",
    "How this pandemic made businesses look back at the basics of operational simplicity.",
    "Importance of being agile in launching products or services.",
  ],

  pullQuote:
    "It is not about building huge products anymore. If the product can solve the problem, it does not need to be fancy. It just needs to solve that problem.",

  exchanges: [
    {
      question:
        "I would like to start with your journey being an author and your other passions of mobilising the youth through various digital media initiatives.",
      answer: [
        "In terms of the book, it is a completely different journey. It is quite interesting. I did my master's in applied psychology and coaching, and while I was doing my master's, I had a classmate with whom I would often be talking about coaching and how we can create lasting change. That is because many times people go for a workshop and get extremely excited and motivated for maybe a week or two. But after that, it just dwindles. It does not last long. So, we were thinking about how we create lasting change, and we were talking about how habits are something that stays with us for a very long time. Also, a habit is not formed overnight, and it does not just start suddenly. It comes with much internal fuel, which we call attitude. It is about the attitude towards a specific item. For example, especially around the new year, many people come up with new year's resolutions, and it probably lasts for two or three months, and then it just drops. It could be starting a new diet or exercising, but there is no reason why somebody wants to do it. Because there is no why behind it, it flops. This is where we wrote the book about habit, with the idea and focus on lasting change. But to get that lasting change, you also need the right attitude towards it. So that is why you have attitude combined with habits, and so it becomes Habitudes. That is the book part of it.",
        "However, how I got into tech is quite a different story. I have always been into psychology, and it has always been about understanding humans better: how do you get people excited about something? How do you get them to learn something faster? It was always around that. My past few careers have always been about education: how do I get people educated about products and different fields. But I got into technology when I started to get people to use our technology products. It was with iCar Asia. And while I was there, the first role I was involved in was taking care of the new products' training. iCar Asia's main customers are car dealers, and car dealers are people who are not that tech-savvy. So, if you were to give your smartphone to your grandparents, they would go: what is this? They would prefer having a phone with buttons instead. And that is the same situation with the car dealers as well. To start educating the users on how to use that product, we had to break it down to something simple and easy for people to digest; otherwise, they will not be bothered. It is like teaching your grandparents how to play Candy Crush or how to use WhatsApp. And suddenly, they will be addicted to the phone. But before we could educate people about the product, I had to understand the product and find the reason we built it, why we did those actions within the web and app products we have. Part of the product learning itself got me involved with the whole product and the strategy behind it, because while I had first-hand experience with the users themselves while we were building the product, it is so important to have that communication with the users. That communication allowed me to understand the product and build future relevant products for those users. I started looking at the future itself; it was not just about the current product we should have, because there are still many gaps that are not filled just yet, and we planned to fill those gaps. Today, if I look at this whole strategy which we have mapped out, it is mapped out for another two to three years ahead, depending on how the economy works and what triggers and initiates that action. To sum it up, it all started by understanding the product, finding out the problems with it, and then that is where it landed me as the head of strategy.",
        "I think the one thing which has always been a constant, regardless of the book about human development in psychology or the product, is that the main gist of everything has always been human. It has always been about understanding people better before developing a strategy to create a product for them. You need to understand who is choosing a product and why they need to use it. So, I think the psychology background allowed me to really have that empathy with the users, and also being able to look at the surroundings to be able to dive into the individual's thought process, take a step back to look at the broader view before concluding. So, I think the human aspect of everything was particularly important.",
      ],
    },
    {
      question:
        "You have been pioneering digital initiatives in the companies that you have been working with. So, how did the digital-first industry evolve over the last three years? And during the pandemic, what is your observation? How did the pandemic affect the digital space?",
      answer: [
        "There has been a large change in the past few years, even for my products, because I think there are many gaps that we are still trying to fix, trying to digitalise and improve the whole process. In terms of the past three years, when we look at the whole user journey of items, many things are becoming digital. If I look at something as simple as grocery shopping, it has transformed, and now we have started buying groceries online, and now even same-day delivery of groceries. So, I think the whole shift in how people are transacting has changed dramatically. The biggest shift of all will be coming with the speed of things, that is, how fast things are being done right now. COVID was an accelerator because many things we wanted to do, which took our time when we had to go to the place and touch items, are now being sent to us through online orders. It is like today your groceries run out, you need them to cook for dinner, and you can get them as fast as possible. So, speed is something that I think has improved a lot over the past couple of months, especially during the COVID time.",
        "Second, I would say it is accessibility. When we talk about accessibility, it is accessibility to the internet and to complete solutions. Previously, we talked about Grab and Uber, which are popular right now all around, and that has opened up whole new access for us where we get a ride anywhere with just a few clicks on the phone. The most important part, which has accelerated all this, especially during the COVID time, is the final mile. Normally people talk about the final mile as the delivery service. But I think the whole idea of the final mile should be looked at in a slightly broader sense, where the final mile is how do you get your product back offline? Because not everybody is rushing online and deciding to move to ecommerce. Everything is influenced by COVID everywhere, but not everyone is going for Lazada or Shopee or starting their own ecommerce platform.",
        "Because the thing is that as much as one goes online, the end product we are all getting is offline. And since we are now talking about bringing it back offline, it is important to ensure that the whole journey is fulfilled. Some food delivery apps in Malaysia are charging 30% to the sellers to list their food in the app. At the same time, they are charging the people who are ordering the food. So, they are charging both ways. Anybody would find that not okay, as the delivery app or the middleman is charging both sides. So, if you look at that final mile situation we are in right now, we are still in a monopolistic situation where just a few businesses control it. Both the sellers and buyers need to be liberated, and that is possible when the final mile starts expanding. It is time for the offline delivery service to expand, and we will have more choices within the next couple of months. As much as we are going digital, these companies will have to bring that journey back to their consumer offline. So, I think there is so much gap in this now. Even if you think about tourism, there is a spike in online tourism, but online tourism is restricted to seeing and hearing and not feeling it. Businesses should try to give people a sense of offline, even though they are stuck at home.",
        "So, I do believe that this whole journey is really about improving that speed, the accessibility, giving the consumers a feel of the final mile, bringing it back offline all over again.",
      ],
    },
    {
      question:
        "What kind of trends are you observing in brands' digital strategies to gain and have a competitive advantage?",
      answer: [
        "Removal of the middlemen. We have always had that middle person in between every transaction, like in property, insurance, or even in the mortgage and loan business. Last year, one of the world's largest insurance companies announced that they would cut down the insurance agents' commission rates. At the end of the day, if we review the whole organisation structure, we will find many aspects that can be streamlined and made non-redundant. This will come with many people losing their jobs, but it will also come as an opportunity to open another brand-new sector.",
        "As much as we do not need agents in the field, we will still need people to maintain all AI systems. Speaking of it, the banks in Malaysia restudied their operations and digitalised things by reducing the workforce. Again, I am concerned about the jobs that people will lose because of this, but we already saw how Uber, Grab, and Gojek started the new digital commerce revolution and created jobs that did not exist previously. So, I think digitalisation will also fill many gaps in between as well. So that is one thing which I foresee happening in the future. It all starts with a whole domino that starts flipping down. If we are imagining COVID-19 as the catalyst that did the first push of the domino to fall, it forced us to review and rethink many of our businesses. Almost every company is looking into how their organisational structure is right now, at their spending and costs, and cleaning up what we no longer use. From a tech standpoint, we built so many tools, and nobody uses some of them, and still there is spending to maintain the tools. It is about removing things that you do not need; it could be just the middleman or the technology, to simplify the business operations. It should have happened before COVID, but nobody focused on it until things happened.",
      ],
    },
    {
      question:
        "Unlike regular business planning, this time in COVID there is no playbook to plan out things. As a digital strategist, what are your recommendations to businesses planning out their next year's strategy from a digital standpoint?",
      answer: [
        "In my view, there has always been a playbook; it is just that we never followed through with it. Because we have always been looking at the North Star, wanting to hit the target, but we never really bothered about it until we are forced to look at it. So that is an interesting thing about COVID. All companies can start reviewing their processes, the customer journey, and visualising small bits and pieces of it. I recently had a discussion with Abby, who used to be the CEO of Shaves2U Malaysia, which is a razor subscription business. It is a subscription service where every month or every three months they send you razors automatically. So, something as simple as that can be digitalised. And it can be turned into something which is a recurring subscription for the users. From his journey, it was evident that he reviewed how consumers purchase razors to understand what the customer journey is. They have made it simpler by allowing consumers to buy online and create a subscription plan that automatically ensures recurring purchases. Hence, once you look into your user flow and the journey, you will find the same thing, just like how I spoke about the banks earlier that will start reducing the number of runners out there in the field. When you start reviewing your processes, you will find workarounds that we never observed in the past. When COVID came, we only had to look at all this digitalisation and ask how can we simplify it? And how can we bring things digital? But it all starts by looking at the user flow. It is really about why you are doing certain actions, and from there on you can decide how you want to digitalise things or not digitise them. Then to execute a digital strategy, you need a strong team in place.",
        "Secondly, we all will need to move to a more agile structure, because we are monitoring our costs right now and want to be as lean as possible. Often, when we speak to our businesses, immediately what they say is that I want to be able to build massive things, but in COVID time you cannot dream big; you have got to be as prudent as possible. And that is where agile comes in. So, if you must build a product, start with an MVP, and then you iterate. Build a bare minimum product that can go to market.",
        "An example of this is that if you look at Malaysia, we have this bank called Maybank. During the COVID times, Maybank released this thing called Sama-Sama Lokal, which is an ecommerce platform for its partners. All the SMEs on Maybank can list all their items for sale on that Sama-Sama Lokal ecommerce platform; there are no fees charged to the user. So, it is completely free for the users. Consumers can go there, and they can spend there as well. It is an extremely basic ecommerce platform; it just does what it needs to do. It is nothing more than that. You cannot compare it with Lazada or Shopee because they have a solid product. Sama-Sama Lokal is an MVP of an extremely basic product, but it works. And what happened was that during the past couple of months, the last time I had a chat with them, they told me that they had crossed the seven-digit mile in terms of transactions within the Sama-Sama Lokal ecommerce platform, which was very surprising to me because I felt like it is so basic, and nobody is going to use it. But surprisingly, seven figures. That is amazing. When I look at that product itself, I realised that you need to build it as simply as possible to get it out to the market as soon as possible. There is no point in waiting three months to build something nicer. And in three months, who knows, COVID might have ended, and it has changed all over again.",
        "So, we need something small to push out to the market as soon as possible. Once you have released the product, the next thing is how you can get feedback from your customers and reiterate. You need a communication channel that allows your consumers to give you feedback right away. That is the essence of being agile, and we will need to move to that structure.",
        "An example of that is, if someone needs to get from point A to point B faster, we can put them in a car, but when you look at the edge on that, we will not do it with a car; rather, we will give them a skateboard which will surely get them from point A to point B. Not as fast as a car, not as safe as a car, but it gets the job done. After giving them that skateboard, they will share their experience with the skateboard about its stability, speed, and safety. Then we give them maybe a scooter, the one with the bar in front of the board, and so on. So, you iterate, and you improve that product with the feedback. If you had given the customer a car right away, there are two problems. The first problem is that it takes forever for you to get a car compared to a skateboard. And to get your customer happy is going to take you a couple of years. Who knows, maybe the customer did not need the car initially, as the traffic is bad and having a car is a bad idea. Maybe a motorbike can help them get from point A to point B faster. But you would not know that unless you have gone through the whole route of starting with a skateboard, changing it to a scooter, then a motorbike. If you jump straight to a car, you will not see that motorbike coming; you will never know that your users need a motorbike instead. And so that is where it is so important. It is not about building huge products anymore; creating that MVP starts as small as possible. The key here is that if the product can solve the problem, it does not need to be fancy. It does not need to be a world-class thing. It just needs to solve that problem. That is the main thing. So, I think agile plays a very important role in this generation right now, especially with COVID.",
      ],
    },
  ],
};
