import type { ExpertInterview } from "../types";

export const anilGautam: ExpertInterview = {
  slug: "anil-gautam",
  project: "south-east-asia-response-guide",
  perspective: "buyer",

  metaTitle: "Focus on the Last-Mile Delivery",
  metaDescription:
    "Anil Gautam, Managing Director at DHL eCommerce Malaysia, on absorbing a 3x volume jump, breaking systems into microservices, and the delivery models emerging in SEA.",

  title: "Focus on the Last-Mile Delivery",
  person: {
    name: "Anil Gautam",
    role: "Managing Director",
    company: "DHL eCommerce Malaysia",
  },

  thumbnail: "/experts/anil-gautam.jpg",
  thumbnailAlt: "Anil Gautam, Managing Director at DHL eCommerce Malaysia",

  intro: [
    "Managing Director at DHL eCommerce Malaysia, Anil Gautam shares his wisdom on countering uncertain markets and navigating businesses seamlessly in the new normal.",
    "In this Research NXT interview, Anil talks to us about creating a strong DHL footprint in Australia, China, and Southeast Asia from a cross-border and domestic point of view, by being a quality leader despite being a new entrant. Additionally, he gives us valuable insights into how DHL managed the impact of COVID-19 via agile technologies and proactive measures to meet the sudden spike in market demand and expectations.",
  ],

  highlights: [
    "DHL's strategies to manage the impact of COVID-19.",
    "Best practices to navigate businesses in the new normal.",
    "Top three trends that are emerging from a logistics point of view in Southeast Asian markets.",
  ],

  pullQuote:
    "There is no problem starting small. It is okay to start small because it helps you to start quickly, fail quickly, learn quickly, and get started again quickly, thus building things incrementally.",

  exchanges: [
    {
      question:
        "I would like to start with your professional journey and helping DHL come to its position in Southeast Asian markets.",
      answer: [
        "I have been with DHL for 18 years. I started with DHL Express, the most well-known unit in the DP DHL Group, valued for its speed across the globe in international transit. I worked with Express from 2002 till 2015. In 2014, Deutsche Post DHL created DHL eCommerce as part of their strategy to manage the booming ecommerce industry. It is the youngest unit in the DP DHL family, and is focused on domestic and international ecommerce delivery. We entered Asia Pacific in 2015, and that is when I joined the team as part of the founding members. We created a strong footprint in Australia, China, and Southeast Asia from a cross-border point of view. However, a great domestic story was taking shape across Asia and Southeast Asia. We therefore started entering these markets gradually, first with Thailand, then Malaysia, followed by Vietnam.",
        "We identified some key traits of these domestic markets very soon. There are many existing incumbents in the domestic market, and the market is very fragmented, unlike the international space where we compete with a few top players like FedEx and UPS. Not only is there fragmentation, but the incumbent players also hold a large asset base. This takes competition a notch higher. In these markets, we do not have a majority market share, but are regarded as a quality leader. Our positioning has always been as a value for money player when we enter a new market where price counts most. In the domestic markets, we can only charge a premium when the service is a very specialised one, but in most cases it is around the market price to stay competitive. So that is what we did when we entered these markets. We positioned ourselves based on the incremental value that we provide compared to the existing incumbents, and in the process we also identified certain challenges in the market. We did a top-down study to identify market needs. Our senior executives visited the top and mid-sized players in the market to understand their issues. Based on those discussions, we had identified three big issues in this market, all of which were related to customer experience. We took those pain points as guideposts while entering these markets to function well. Overall, I believe we have quality leadership, and we have gained a good market share to date.",
      ],
    },
    {
      question:
        "The sudden and unprecedented spread of COVID-19 took all of us, including every kind of business, by shock. Noteworthy to mention is that the logistics and delivery businesses have kept the wheels of life running even in the toughest times. Can you tell us a little about DHL's efforts to manage the effects of COVID-19?",
      answer: [
        "It was not the first time a pandemic hit this part of the world, but this time the scale was burgeoning. Many countries started lockdowns because of the fear of the unknown. In Malaysia, things were no different. During a lockdown, everybody is confined to their homes, and only essential services like ours get approval to work. So, we continued to operate as per our usual schedules. The first challenge before us was a 3x jump in volumes. Our business was not structured for that level of volume, but we immediately took the following steps to manage this:",
        {
          ordered: true,
          list: [
            "Firstly, we had to revisit the business continuity plans, as they were usually made to handle disasters where volume also takes a hit. However, in this case, we had to handle higher volumes with BCP-based capacity, which was even more difficult because we could not process that much. We prioritised employee safety by creating new SOPs to keep our employees safe from any COVID-related risks. And for that, we had to educate them on keeping themselves and their families safe. We regularly equipped them with all the personal safety equipment, taught them to do contactless delivery, and ensured that they did not have to step out for any meals during work time. This helped us to reduce our employees' interaction with any external factors.",
            "The second thing that we did to handle this volume was to scale up immediately. Scaling up for the domestic market was possible with our flexible structures, where just like Uber, we can add as many couriers as we wish. Everything is controlled by an app, which the courier can access through their mobile phones. It tells them the number of shipments to deliver, where to deliver, how to call the customer, and how to sequence it so that the courier can plan the routes. It also lets DHL track exactly the whereabouts of its deliveries as they happen. So, the app made it very easy for us to increase headcount, and all we had to do was train the new couriers to ensure a good doorstep experience. Through focused guidance and coaching, the new staff could optimise their productivity, thereby increasing the capacity to handle more volumes. We also asked the new couriers to shadow some of our experienced couriers to fast-track their learning curve. That is how we were able to handle the market demand.",
            "The third most important thing that we did was ensuring that we kept the communication loop with our customers frequent and transparent. Lockdown norms were being revised frequently, which meant that we had to change the SOPs frequently and keep educating our couriers in a timely way. Our staff members were also regularly communicating about these new developments, the implications of the new SOPs to our customers, and how it might impact our ability to deliver on time. This helped them to plan their business and keep their own customers informed accordingly as well. Setting up this understanding was critical and helped all stakeholders to maintain balance. Our customers had their share of challenges as well, and hence they understood the limitations: their raw material was not coming to them on time, packaging and supplies were short, labour was also short because some of the labour got scared and did not want to come to work. We have instances where we have worked with our customers to solve some of their issues as well. That is how trust and a long-term bond is built. Meanwhile, buyers also started anticipating and accepting updated delivery timelines: a next-day delivery might become next day plus one in big towns, and it might just take a bit more for other places. Everyone started being a bit patient, and we had to make everyone realise that delivery personnel were also front liners, just like doctors, nurses and police. It was also very interesting to see motivational and appreciation messages and gratitude coming in for our couriers.",
            "The fourth thing that we immediately took up was from a technology point of view. While our software is very agile for all kinds of merchants to create and track shipments easily, we had to boost our systems' server capacities to handle more data. We had to ensure that we have more backups, as there were volume spikes quite often, especially during the festive period of Hari Raya Aidilfitri in Malaysia. This was a period of very high buying activity, so it was very important for us to ensure that we could handle the increased volume on the system side regularly for a duration of 30 to 40 days. So, we boosted our system within a very short time. And fortunately, being a large company, we have enough resources on the cloud to ensure we succeed. So, I think these are the four ways DHL was able to handle the pandemic in Malaysia and keep up the experience of ecommerce.",
          ],
        },
      ],
    },
    {
      question:
        "Innovative and agile business methods, particularly on the digital front, have leapfrogged in the business space owing to the recent pandemic. And logistics players like DHL have been the first to adopt them. Could you share some best practices with the larger business community as they navigate their response to this new normal?",
      answer: [
        "We are already a year into the pandemic, and what we call the new norm is something I think should be treated as the new normal, as times have changed. We have to live with it. I think it taught and compelled us to change how we communicate with each other and our clients. Businesses have become more digitised in the way things are bought, sold, distributed, and even the way payments happen. I am not talking about internet banking, but actual buying and selling between retailers has changed a lot, to the extent that we feel there is nothing called ecommerce, and the new word is just commerce. Businesses and transactions are happening over desktops, mobiles and social media, and everything has changed drastically. That is what we see in this part of the world in Southeast Asia. This prompts people to consume much more through online media and become very open to new brand preferences. People have become more experimental in trying newer brands, and these brands have become very big. For example, in Malaysia, if you had seen a typical report on top online sellers, you would be surprised to see the change in brand names in the top 20. The new players in the market are not necessarily the ones that were captured in the ecommerce world early on; these are the new incumbents. So that is a big change.",
        "It means that businesses have to adapt themselves very fast, and it is not very difficult anymore with multiple options available now for every aspect of a business. These allow customised software to be created on agile platforms. These platforms offer a complete set of capability building options from social media marketing, sales, and channel management on social media through marketplaces, under one roof. So, you can integrate a complete commerce platform with systems encompassing shipping, order management and warehousing. And in addition to that, you can also run your customer service through robotics. The use of robotics is increasingly being seen in many aspects of businesses in Malaysia, not just customer service. I have examples of sellers who in the last year have risen to be among the top sellers in Malaysia by implementing robots as part of their sales team. Their human sales team is not big in size. Everything is mechanised, and interestingly it is so seamless that customers cannot differentiate it from an actual human. What is more, it does not function only in English but also in the local language. So, you can imagine the quantum of change that is happening. Certain businesses that have adapted very quickly to this new regime are on their way to becoming big brands. As they scale up, they will occupy the customer's mind space more and more soon. So, I think it is very important that businesses in every vertical have to become more agile in adopting these new technologies. Having said this, I also think that there is no problem in starting small. It is okay to start small because it helps you to start quickly, fail quickly, learn quickly, and get started again quickly, thus building things incrementally. And once you become a big brand, you can look at something which is end-to-end and a more integrated solution.",
      ],
    },
    {
      question:
        "The new normal and the year forward, unlike every year, would accompany many changes in terms of corporate planning. And you have been at the forefront of using technology. So what are the changes that you see in DHL in 2021 from a business strategy standpoint? What are the top changes you are working on?",
      answer: [
        "With the quantum of business which hit us during the pandemic, we learned a lot. While our systems are very agile, I think there is always room for improvement.",
        "**Systems.** We started breaking our systems into smaller microservices, which helped us quickly integrate with different custom applications. That is one of the important things that we embarked on. We are also investing a lot in the last mile and the first-mile delivery systems to align with such custom applications for a seamless first to last mile alignment. The quantum of volume and flexibility with microservices easily lets us customise to unique customer requirements.",
        "**Digital product offerings.** Secondly, we are becoming more digital in our product offerings. DHL always has a pyramid where we work with the top customers and mid-sized customers, as small customers find us very expensive. So, we are innovating by creating newer digital models to enhance interactions and experiences at lower costs. Our storefront is completely uploaded on the app-based model or a portal-based model, which seamlessly connects and sends real-time tracking alerts to the buyers. So, the customers get everything through one single interface, which can be integrated with various mediums like social media, chats and websites. This allows our customers to track, update and validate their delivery details through any interface, thus minimising a failed delivery. This results in avoiding poor customer experience for the seller as well. So, we try to improve upon aspects like these. Finally, we are looking a lot more at the front-end agility and ensuring the backend can support any customisation required at the front end.",
      ],
    },
    {
      question:
        "You have been at the forefront of the logistics industry. So, what are the top trends you would predict for the logistics space in 2021 and beyond?",
      answer: [
        "In the Southeast Asian context, newer models are emerging for deliveries. Since the cost of labour is low here, most companies provide doorstep deliveries. However, we see more and more requests for deliveries into parcel lockers or DHL parcel shops where customers can come and collect their parcels at their convenience, rather than being left at residences or simply taken back. In 2019, one of our customers started this practice, and it was about 1% to 2% of the total volume because Malaysians prefer doorstep deliveries. But we see an emergence of more people accepting the new collect-it-yourself model where the parcel is safe enough and there is flexibility in terms of acceptance time. So, I think that is one big thing which is emerging.",
        "Secondly, the requirement for multiple choices of delivery options is emerging: same day, next day guaranteed, before 10am delivery. For example, there are different kinds of buyers who transact with various sellers, and they are always on the lookout for multiple kinds of delivery solutions. A pharmacy that sells general merchandise, cosmetics and medicines may have customers with non-conventional delivery needs, ranging from two hours to the same day. In this case, a hub and spoke model will not work, where the parcel is collected from a particular store and delivered to the customer's doorstep within two hours. Another case may be something bought from a local storefront website, but it has to be procured from an international location where DHL does the last mile delivery. So, various models are emerging, and this is just the start of it. Consumers have started embracing these newer models of delivery and are willing to pay a premium too.",
        "The third thing that we see emerging is that smaller and smaller sellers are looking at cheaper delivery models. They do not subscribe for pickup and will come to our collection centre to save on the pickup charges. Here, we are providing them with more affordable solutions that are making them more marketable. And as they become more marketable, they scale up because of the increased volume and gradually opt for the pickup services. More stores are coming across Malaysia because of the latest boom in ecommerce, where small and medium enterprises can walk in, send a shipment, and rest assured that it is already there in the network. So, I think these are the three trends that we are seeing emerging from a logistics point of view in Southeast Asia.",
      ],
    },
  ],
};
